# Generated by Django 6.0.5 on 2026-05-30 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('last_recorded_photo', models.ImageField(blank=True, null=True, upload_to='locations/')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('race', models.CharField(max_length=100)),
                ('is_dangerous', models.BooleanField(default=True)),
                ('last_recorded_photo', models.ImageField(blank=True, null=True, upload_to='characters/')),
                ('last_known_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='PalInTears.location')),
            ],
        ),
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('faction', models.CharField(choices=[('ORCS', 'Orcs'), ('ELVES', 'Elves'), ('DWARVES', 'Dwarves'), ('MEN', 'Men'), ('MONSTERS', 'Monsters')], max_length=50)),
                ('size', models.IntegerField(default=0)),
                ('last_recorded_photo', models.ImageField(blank=True, null=True, upload_to='armies/')),
                ('last_known_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armies', to='PalInTears.location')),
            ],
        ),
    ]
